### ISSUE TITLE
Powershell Client Authentication Failure

### ISSUE THREAD

**Issue by lmkelly** [thedunston/sshwireguard#11]
While running through the install process on windows I ran into an issue when I tried to run the windows client script.

![Capture](https://user-images.githubusercontent.com/45275395/112930479-5ce11780-90e8-11eb-8f71-e7a77b4275bd.PNG)

It threw out the invoke-webrequest red-test error only when I attempted a root login, otherwise I was given just the error downloading the VPN configuration error and sent out.

I also experienced trouble on the server-side adding the extra line to the visudo file. I added the line with the hostname of the localhost because that's the host I was running the webserver on but every time I elevated to root it threw this error

![Capture](https://user-images.githubusercontent.com/45275395/112930748-dbd65000-90e8-11eb-9fcf-48b02ed928e7.PNG)

Let me know if you want any more information, I wasn't able to get this error sorted out.

**Comment by thedunston** [comment]
On your web server, type:

hostname

that is the hostname you want to use in your sudoers file.

**Comment by thedunston** [comment]
Did you get this working?

**Comment by lmkelly** [comment]
yes! thank you
