### ISSUE TITLE
Windows Client PowerShell Script Wireguard Install Issue

### ISSUE THREAD

**Issue by bronsonleclerc** [thedunston/sshwireguard#2]
When running the "WindowsNowireVPN.ps1" script on an unconfigured Windows client, I get the error in the attached screenshot.  I troubleshoot the issue, and I think it is related to the Wireguard version that the script tries to download.  It seems like the script points to "https://download.wireguard.com/windows-client/wireguard-amd64-0.1.1.msi", but when I browsed to the URL, the only installer I was able to find was "https://download.wireguard.com/windows-client/wireguard-amd64-0.3.8.msi".  I changed the $wg_file variable to the 0.3.8 version and the error went away.  

Not sure if it would be possible to have the PowerShell script determine the current version to download more dynamically to ensure it will continue working with new versions? 

Thanks!

![Capture](https://user-images.githubusercontent.com/47750436/111911150-b4251f00-8a3a-11eb-872a-4bc55fb54ad6.PNG)

**Comment by thedunston** [comment]
Thank you for the report.  The Windows client is now "wireguard-installer.exe" on the wireguard download page and the Powershell script has been updated to reflect the change.
