### ISSUE TITLE
Receiving Error adding user when trying to run the nowire client script

### ISSUE THREAD

**Issue by kassarole** [thedunston/sshwireguard#4]
I was able to get a nowire server configured on an AWS box which can be reached publically. The client script is able to properly connect to the server via ssh but when attempting to create the user configuration it fails with the message Error adding user.

**Comment by thedunston** [comment]
Which option are you running and what error appears in your apache error log file?

Also, ensure you added the web user to sudo to run the script:

www-data hostname = NOPASSWD: /bin/bash /var/peers/wireguard-nowire/tmp/wg-add.bash

**Comment by Tetoronie** [comment]
I had the same issue but doing this solved it. Thanks!

**Comment by kassarole** [comment]
This fixed it for me too thank you!

**Comment by thedunston** [comment]
That step is already in the README under "Sudo Setup."  However, I'll update the README and will echo that last step after everything else is set up so it stands out that it needs to be done.

Thank you for the feedback.

**Comment by thedunston** [comment]
The README has been updated and the documentation added to the wiki and separated out.
