### ISSUE TITLE
Custom install doesn't allow user to input options

### ISSUE THREAD

**Issue by keeperazra** [thedunston/sshwireguard#7]
Running `sudo ./wireguard-server.sh --install` shows all the configuration dialogs for a brief moment, but no input is collected from the user, and it jumps immediately to installing dependencies. I see the same behavior upon attempting a headless install as well. Incidentally, if I supply --uninstall during a headless install, I am able to properly chose configuration options. Which is really strange. Not sure if any other combination of options functions differently, as I have not tested them at the moment.

**Comment by thedunston** [comment]
I am not able to duplicate this issue.  Be sure that you haven't installed Wireguard on the system or remove the /etc/wireguard directory.

On a clean system, I am getting the prompts to enter settings manually using ./wireguard-server.sh --install

**Comment by keeperazra** [comment]
Strange, on a fresh instance of Ubuntu Server 20.04 LTS (HVM), I can replicate this issue, and confirm that Wireguard was not installed and that /etc/wireguard did not exist prior to executing the script. I'm wondering if there is something about the EC2 instance that just doesn't play well with the script? Either way, I'll see if I can come up with any more details.

**Comment by keeperazra** [comment]
It looks like `--install` sets `HEADLESS_INSTALL` to y, even if not specified by the user.
https://github.com/thedunston/nowire/blob/18ca0b8764b49d42fc3341012d7c950862d7ef28/wireguard-server.sh#L147-L149

It looks like the script functions properly if I don't specify --install, or if I run it like `sudo HEADLESS_INSTALL=n ./wireguard-server.sh --install`

**Comment by thedunston** [comment]
- Thank you for the additional details.  The problem has been fixed by changing line 149 from: 

 HEADLESS_INSTALL=${HEADLESS_INSTALL:-y} 

to

HEADLESS_INSTALL=${HEADLESS_INSTALL:-n}
