### ISSUE TITLE
client-nowire.bash Maximum VPN IPs

### ISSUE THREAD

**Issue by joseph-thetford** [thedunston/sshwireguard#9]
I get the below output when running the client-nowrire.bash script when maximum VPN IPs is set to 0 in the running of nowire-setup.bash on the server (which should allow for infinite IPs). The problem is resolved when I run the nowire setup again and input a greater number.

![image](https://user-images.githubusercontent.com/54678845/112924077-792b8700-90dd-11eb-9328-9fe05092adea.png)

**Comment by thedunston** [comment]
Thank you for the report.  The issue has been fixed.  When it is set to 0, a check for the number of client configurations is ignored.
